# Pandas Intro

In [1]:
import pandas as pd

### Create series & dataframe objects

In [3]:
numbers = [1,2,3,4,5]

number_series = pd.Series(numbers)

In [4]:
numbers

[1, 2, 3, 4, 5]

In [7]:
number_series

# creates an automatic range of indices to label each list element

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
pd.Series(numbers, index=['a','b','c','d','e'])

# you can specify the index used
# no. of elements must match

a    1
b    2
c    3
d    4
e    5
dtype: int64

### Dictionary: Key - Vaue pairs

In [10]:
cities = {"Nakuru":130000,"Voi":250000,"Kwale":125000}

pop = pd.Series(cities)
pop

Nakuru    130000
Voi       250000
Kwale     125000
dtype: int64

### Creating DataFrame objects

In [11]:
# from a list

data = [["Alice",25,"Kwale"], ["Bob",30,"Turkana"], ["Charlie",26,"Nairobi"]]
pd.DataFrame(data)

         0   1        2
0    Alice  25    Kwale
1      Bob  30  Turkana
2  Charlie  26  Nairobi

In [ ]:
# specifying column names

pd.DataFrame(data, columns=["Name", "Age", "City"])

      Name  Age     City
0    Alice   25    Kwale
1      Bob   30  Turkana
2  Charlie   26  Nairobi

In [ ]:
# from a dictionary of lists

data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 26],
        'City': ['Kwale', 'Turkana', 'Nairobi']}

pd.DataFrame(data)

      Name  Age     City
0    Alice   25    Kwale
1      Bob   30  Turkana
2  Charlie   26  Nairobi

In [ ]:
# from a dictionary of series objects

name_series = pd.Series(['Alice', 'Bob', 'Charlie'])
age_series = pd.Series([25, 30, 26])
city_series = pd.Series(['Kwale', 'Turkana', 'Nairobi'])

df = pd.DataFrame({"Name":name_series, "Age":age_series, "City":city_series})

df

      Name  Age     City
0    Alice   25    Kwale
1      Bob   30  Turkana
2  Charlie   26  Nairobi

## Reading into a DataFrame object

In [ ]:
df = pd.read_csv(r"D:\2-zindua\03-python-data-analysis\zindua-python-data-analysis\wk2_pandas\mobile_sales.csv")

# the 'r' is telling python to consider the backslashes literally

df.head(2)  # with no param, it prints the first 5 rows

,TransactionID,Date,MobileModel,Brand,Price,UnitsSold,TotalRevenue,CustomerAge,CustomerGender,Location,PaymentMethod
0,79397f68-61ed-4ea8-bcb2-f918d4e6c05b,2024-01-06,direction,Green Inc,1196.95,85,28002.80,32,Female,Port Erik,Online
1,4f87d114-f522-4ead-93e3-f336402df6aa,2024-04-05,right,Thomas-Thompson,1010.34,64,2378.82,55,Female,East Linda,Credit Card

In [19]:
data = pd.read_csv(r"D:\2-zindua\03-python-data-analysis\zindua-python-data-analysis\wk2_pandas\mobile_sales.csv")

data.head(2)

,TransactionID,Date,MobileModel,Brand,Price,UnitsSold,TotalRevenue,CustomerAge,CustomerGender,Location,PaymentMethod
0,79397f68-61ed-4ea8-bcb2-f918d4e6c05b,2024-01-06,direction,Green Inc,1196.95,85,28002.80,32,Female,Port Erik,Online
1,4f87d114-f522-4ead-93e3-f336402df6aa,2024-04-05,right,Thomas-Thompson,1010.34,64,2378.82,55,Female,East Linda,Credit Card

In [ ]:
df.tail(3)  # prints last (n) rows

,TransactionID,Date,MobileModel,Brand,Price,UnitsSold,TotalRevenue,CustomerAge,CustomerGender,Location,PaymentMethod
997,e6839305-a177-4cda-aada-3ac1f49eeeec,2024-01-13,enjoy,"Atkinson, Moore and Nelson",544.31,59,1381.82,26,Female,Barneschester,Credit Card
998,12f7ac32-9063-4ae5-a122-385b06ba77af,2024-01-25,half,"Kim, Maxwell and Moore",331.98,84,8557.32,20,Male,Jonesborough,Online
999,d3e82026-2084-40f2-8d5d-d2a94a198af9,2024-01-17,fill,Wallace LLC,973.97,79,70739.76,44,Female,Port Luis,Credit Card

### Print a summary of the dataset

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   TransactionID   1000 non-null   object
 1   Date            1000 non-null   object
 2   MobileModel     1000 non-null   object
 3   Brand           1000 non-null   object
 4   Price           1000 non-null   float64
 5   UnitsSold       1000 non-null   int64
 6   TotalRevenue    1000 non-null   float64
 7   CustomerAge     1000 non-null   int64
 8   CustomerGender  1000 non-null   object
 9   Location        1000 non-null   object
 10  PaymentMethod   1000 non-null   object
dtypes: float64(2), int64(2), object(7)
memory usage: 86.1+ KB

In [ ]:
data.columns    # prints column names

Index(['TransactionID', 'Date', 'MobileModel', 'Brand', 'Price', 'UnitsSold',
       'TotalRevenue', 'CustomerAge', 'CustomerGender', 'Location',
       'PaymentMethod'],
      dtype='object')

In [ ]:
data.shape  # prints shape (rows, columns)

(1000, 11)

In [26]:
data.describe()

             Price    UnitsSold   TotalRevenue  CustomerAge
count  1000.000000  1000.000000    1000.000000  1000.000000
mean    807.512970    50.074000   40218.445040    41.141000
std     402.489878    28.616804   32715.290358    13.528346
min     103.320000     1.000000     116.850000    18.000000
25%     458.037500    25.000000   13316.037500    29.000000
50%     823.730000    51.000000   30860.655000    41.000000
75%    1157.875000    75.000000   60770.435000    53.000000
max    1499.250000    99.000000  141411.840000    64.000000

In [ ]:
data.dtypes # data types of each column

TransactionID      object
Date               object
MobileModel        object
Brand              object
Price             float64
UnitsSold           int64
TotalRevenue      float64
CustomerAge         int64
CustomerGender     object
Location           object
PaymentMethod      object
dtype: object